Repository ODIM-Project/PluginCiscoACI, pull requests merged in 2021-03, with the labels that each got.

#12 Issue 1 task 5 Packaging and deployment solution with kubernetes
  build/Dockerfile.aciplugin
  build/Dockerfile.builddep
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build_images.sh
  install/Docker/dockerfiles/Dockerfile.aciplugin
  install/Docker/dockerfiles/scripts/add-hosts/add-hosts.go
  install/Docker/dockerfiles/scripts/add-hosts/go.mod
  install/Docker/dockerfiles/scripts/add-hosts/go.sum
  install/Docker/dockerfiles/scripts/start_aciplugin.sh
  install/Kubernetes/helmcharts/aciplugin-config.yaml
  install/Kubernetes/helmcharts/aciplugin/Chart.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/_helpers.tpl
  install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/deployment.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/pv.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/pvc.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/service.yaml
  install/Kubernetes/helmcharts/aciplugin/values.yaml
  install/Kubernetes/helmcharts/deploying_chart.sh
  install/Kubernetes/helmcharts/undeploy_chart.sh
  install/README.txt
Labels: prio:high, status:in-progress, type:bug

#14 Aci 6:Adding switch info in the Managers response
  caphandler/managers.go
  go.mod
  go.sum
Labels: prio:normal, status:resolved, type:feature

#16 Aci 6: Adding additional attributes in Port response
  caphandler/fabrics.go
  caphandler/managers.go
  caphandler/ports.go
  caphandler/switches.go
  caputilities/aciClient.go
  go.mod
  go.sum
  main.go
Labels: prio:normal, status:in-progress, type:feature

#18 issue-10 task 1: Add APICConf to the config map to make it configurable
  install/Kubernetes/helmcharts/aciplugin-config.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
  install/Kubernetes/helmcharts/aciplugin/values.yaml
Labels: prio:high, status:incomplete, type:bug

#19 Aci 15:Adding Post,Get Collection and Get on address pool
  capdata/data.go
  caphandler/addresspools.go
  main.go
Labels: prio:normal, status:in-progress, type:feature

#20 aci 15:Use the GatewayIPAddress attribute instead of HostAddressRange
  caphandler/addresspools.go
Labels: prio:normal, status:in-progress, type:feature

#21 aci 15:Adding delete operation for Addresspool
  capdata/data.go
  caphandler/addresspools.go
  main.go
Labels: prio:normal, status:in-progress, type:feature

#22 Default Zone Creation, Retrieval and Deletion
  capdata/data.go
  caphandler/zones.go
  caputilities/aciClient.go
  go.mod
  go.sum
  main.go
Labels: prio:normal, status:in-progress, type:feature

#24 Aci 15:Adding BD creation in Zone of Endpoints
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#25 Odim 4380: Create VRF with conflict checks in ZoneOfZones
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#27 Odim 4380: Delete Application profile and VRF
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#26 Aci 15:Adding creation of Subnets in zone of Endpoints
  caphandler/addresspools.go
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#28 aci 15:Link BD and VRF during Zone of Endpoints Creation
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#29 Aci 15 :Adding NativeVLAN attribute in the Addresspool
  caphandler/addresspools.go
Labels: prio:normal, status:in-progress, type:feature

#30 aci 15:Considering one AddressPool during creation of Zone of Endpoints
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#31 aci 15:Adding logic to create EPG and link EPG to BD
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#32 aci 15:Adding logic to link EPG to domain
  caphandler/zones.go
  config/config.go
  config/config.json
Labels: prio:normal, status:resolved, type:feature

#33 Aci 15:Adding logic to delete ZoneOfEndpoints
  caphandler/addresspools.go
  caphandler/zones.go
  go.mod
  go.sum
Labels: prio:normal, status:in-progress, type:feature

#34 Issue 17 task 1: Add DB connecting functions
  README.md
  capmodel/aciPort.go
  capmodel/aciPort_test.go
  capmodel/common.go
  capmodel/common_test.go
  capmodel/zone.go
  capmodel/zone_test.go
  config/config.go
  config/config.json
  config/constants.go
  config/mockconfig.go
  config/mockconfig_test.go
  db/client.go
  db/client_test.go
  db/operations.go
  go.mod
  go.sum
Labels: prio:normal, status:in-progress, type:techdebt

#40 Dockerimage build fix
  install/Docker/dockerfiles/Dockerfile.aciplugin
  install/Kubernetes/helmcharts/aciplugin-config.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
  install/Kubernetes/helmcharts/aciplugin/values.yaml
Labels: prio:high, status:in-progress, type:bug

#37 Aci 36:Adding contract creation in ZoneofZone creation
  Makefile
  build/Dockerfile.builddep
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#42 Aci 41 task1:Adding the Post and Get Handlers for endpoints
  capdata/data.go
  caphandler/endpoints.go
  caphandler/ports.go
  caputilities/aciClient.go
  go.mod
  go.sum
  main.go
Labels: prio:normal, status:in-progress, type:feature

#43 Typo fix
  install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
Labels: prio:high, status:in-progress, type:bug

#46 Compilation deployment fixes
  install/Docker/dockerfiles/Dockerfile.aciplugin
  install/Kubernetes/helmcharts/aciplugin-config.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
  install/Kubernetes/helmcharts/aciplugin/values.yaml
Labels: prio:high, status:in-progress, type:techdebt

#44 Aci 41 task2:Adding validation in creation of endpoints and adding logic to delete endpoint
  caphandler/endpoints.go
  caphandler/zones.go
  go.mod
  go.sum
Labels: prio:normal, status:resolved, type:feature

#48 Workflow developed to compile and run unit_test
  .github/workflows/build_unittest.yml
Labels: prio:high, status:in-progress, type:techdebt

#50 Patch on Ports to handle attach of connected ports
  caphandler/ports.go
  caputilities/aciClient.go
  config/config.go
  config/config.json
  main.go
Labels: prio:normal, status:in-progress, type:feature

#51 issue-17 : updated config chart with DB conf data and VerifyPeer to false
  install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
Labels: prio:normal, status:in-progress, type:feature

#53 Helm manifest file update- configmap.yaml
  install/Kubernetes/helmcharts/aciplugin-config.yaml
  install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
  install/Kubernetes/helmcharts/aciplugin/values.yaml
Labels: prio:high, status:in-progress, type:techdebt

#56 Aci 52:Creating domain and Policy group in ACI
  capdata/data.go
  caphandler/addresspools.go
  caphandler/chassis.go
  caphandler/endpoints.go
  caphandler/ports.go
  caphandler/zones.go
  capmodel/aciEntityHealth.go
  capmodel/fabricHealth.go
  caputilities/aciClient.go
  config/config.go
  main.go
Labels: prio:normal, status:in-progress, type:feature

#57 Aci 54:Adding support for patch on zone of Endpoints
  caphandler/zones.go
  main.go
Labels: prio:normal, status:in-progress, type:feature

#60 aci-58:Updating the VLAN usage using VLANIdentifierAddressRange
  caphandler/addresspools.go
  caphandler/zones.go
Labels: prio:normal, status:in-progress, type:feature

#61 issue-17 : persist port data in db
  capdata/data.go
  caphandler/addresspools.go
  caphandler/endpoints.go
  caphandler/managers_test.go
  caphandler/ports.go
  caphandler/zones.go
  capmodel/aciPort.go
  capmodel/addresspools.go
  capmodel/common.go
  capmodel/common_test.go
  capmodel/endpoints.go
  capmodel/fabric.go
  capmodel/switchChassis.go
  capmodel/zone.go
  capmodel/zone_test.go
  db/constants.go
  db/mockOperations.go
  db/operations.go
  main.go
Labels: prio:normal, status:resolved, type:feature

#63 issue-17 : clean up redundant code
  caphandler/managers_test.go
  capmodel/aciPort.go
  capmodel/aciPort_test.go
  capmodel/addresspools.go
  capmodel/common.go
  capmodel/common_test.go
  capmodel/endpoints.go
  capmodel/fabric.go
  capmodel/fabric_test.go
  capmodel/switchChassis.go
  capmodel/zone.go
  capmodel/zone_test.go
  db/constants.go
  db/mockOperations.go
Labels: prio:normal, status:in-progress, type:feature
