Repository ODIM-Project/PluginCiscoACI, pull requests merged in 2021-02, with the labels that each got.

#5 Issue 1 task 4 Packaging and deployment solution with docker
  Makefile
  README.md
  build/Dockerfile.aciplugin
  build/Dockerfile.builddep
  build/build.sh
  build/cleanup.sh
  build/command.sh
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build/makedep.sh
  build/plugin.service
  build/start_plugin.sh
  caphandler/basicAuth.go
  capmodel/devices.go
  capresponse/errorResponse.go
  config/config.json
  config/platformconfig.toml
Labels: bug

#8 Aci 7:Adding manager schema in ACI plugin
  caphandler/managers.go
  caphandler/managers_test.go
  go.mod
  go.sum
  main.go
Labels: prio:normal, status:in-progress, type:feature

#9 Aci 6:Adding logic to query Fabric and Switch port information of configured fabric
  Makefile
  build/Dockerfile.builddep
  capdata/data.go
  caphandler/fabrics.go
  caphandler/managers.go
  caphandler/switches.go
  caputilities/aciClient.go
  config/config.go
  config/config.json
  constants/constant.go
  go.mod
  go.sum
  main.go
Labels: prio:normal, status:rejected, type:feature

#11 ACI 6:Retreving the switch ports information during plugin start up
  capdata/data.go
  caphandler/ports.go
  capmodel/aciPort.go
  caputilities/aciClient.go
  go.mod
  go.sum
  main.go
Labels: prio:normal, status:in-progress, type:feature
