Repository ODIM-Project/PluginCiscoACI, pull requests merged in 2022-02, with the labels that each got.

#92 Merge to Dev- Update CiscoACI docker image version and add a missed step in deployment instructions
  README.md
Labels: type:doc

#93 Updated cipher suites
  config/config.json
  config/mockconfig.go
  install/Kubernetes/helmcharts/aciplugin/templates/configmaps.yaml
Labels: prio:normal, status:in-progress, type:techdebt

#87 Odim 53:Updating the uptime in cisco aci plugin
  caphandler/pluginStatus.go
  caputilities/utility.go
  main.go
Labels: prio:normal, status:in-progress, type:bug

#94 Docker image and helmchart tag version update
  build_images.sh
  install/Kubernetes/helmcharts/aciplugin/Chart.yaml
  install/Kubernetes/helmcharts/aciplugin/values.yaml
Labels: prio:high, status:in-progress, type:feature

#95 Updating the latest lib-utilities from ODIM in ACI
  go.mod
  go.sum
  main.go
Labels: prio:high, status:in-progress, type:bug

#96 Merge to dev - Updating relevant feedback items given for the plugin sections in the Getting Started readme
  README.md
Labels: type:doc

#98 Merge to Release branch - Updating relevant feedback items given for the plugin sections in the Getting Started readme
  README.md
Labels: type:doc
